### ISSUE TITLE
About the data processing

### ISSUE THREAD

**Issue by wys2929** [maoyunyao/CMD#2]
**train_data_joint.npy** and **train_num_frame.npy** respectively is what documents, how to make data pretreatment. Looking forward to your reply!

options_pretraining.py:
// feeder
   self.train_feeder_args = {
     'data_path': './data/NTU-RGB-D-60-AGCN/xsub/train_data_joint.npy',
     'num_frame_path': './data/NTU-RGB-D-60-AGCN/xsub/train_num_frame.npy',
     'l_ratio': [0.1,1],
     'input_size': 64
   }

**Comment by maoyunyao** [comment]
Please refer to: https://github.com/fmthoker/skeleton-contrast
